#Requires -Version 5.1
param(
    [switch]$Install,
    [switch]$SkipNative
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path (Join-Path $Root "settings.gradle.kts"))) {
    throw "Cannot locate clients/android root (expected settings.gradle.kts next to scripts/)."
}
Set-Location $Root

function Resolve-JavaHome {
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\java.exe"))) {
        return $env:JAVA_HOME
    }
    foreach ($candidate in @(
        (Join-Path $Root "tools\jdk-17"),
        (Join-Path $env:USERPROFILE "tools\jdk-17"),
        "C:\Program Files\Microsoft\jdk-17*",
        "C:\Program Files\Eclipse Adoptium\jdk-17*"
    )) {
        $resolved = Get-Item $candidate -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($resolved -and (Test-Path (Join-Path $resolved.FullName "bin\java.exe"))) {
            return $resolved.FullName
        }
    }
    throw "JAVA_HOME not set and JDK 17 not found. Install JDK 17 and set JAVA_HOME (see docs/BUILD.md)."
}

function Resolve-AndroidSdk {
    foreach ($candidate in @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        "C:\Android\Sdk",
        (Join-Path $env:LOCALAPPDATA "Android\Sdk")
    )) {
        if ($candidate -and (Test-Path $candidate)) {
            return $candidate
        }
    }
    throw "Android SDK not found. Set ANDROID_HOME or ANDROID_SDK_ROOT."
}

$javaHome = Resolve-JavaHome
$sdk = Resolve-AndroidSdk
$env:JAVA_HOME = $javaHome
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk

@"
## This file is generated by scripts/build-apk.ps1
sdk.dir=$($sdk -replace '\\', '/')
"@ | Set-Content -Path (Join-Path $Root "local.properties") -Encoding ASCII

Write-Host "JAVA_HOME=$javaHome"
Write-Host "ANDROID_SDK=$sdk"

# Approved branding icons (from Assets/Branding master)
& (Join-Path $PSScriptRoot "generate-branding.ps1")
if (-not $?) { throw "generate-branding.ps1 failed" }

# Frozen Core provenance (must not change)
$assertCore = Join-Path $Root "..\windows\scripts\assert-frozen-core.ps1"
if (Test-Path $assertCore) {
    Write-Host "==> Assert Frozen Core"
    & $assertCore
    if ($LASTEXITCODE -ne 0) { throw "Frozen Core assert failed" }
}

if (-not $SkipNative) {
    Write-Host "==> Native bridge (gomobile)"
    & (Join-Path $PSScriptRoot "build-native.ps1")
    if ($LASTEXITCODE -ne 0) { throw "build-native.ps1 failed" }
} else {
    $aar = Join-Path $Root "bridge\native\nyxveilbridge.aar"
    if (-not (Test-Path $aar)) {
        throw "SkipNative set but AAR missing: $aar"
    }
    Write-Host "SkipNative: using existing $aar"
}

$gradlew = Join-Path $Root "gradlew.bat"
& $gradlew ":bridge:testDebugUnitTest" ":app:testDebugUnitTest" ":app:assembleDebug"
if ($LASTEXITCODE -ne 0) {
    throw "Gradle build failed with exit code $LASTEXITCODE"
}

$version = (Get-Content (Join-Path $Root "VERSION") -Raw).Trim()
$apkSrc = Join-Path $Root "app\build\outputs\apk\debug\app-debug.apk"
if (-not (Test-Path $apkSrc)) {
    throw "APK not found: $apkSrc"
}

# APK native content gate
Add-Type -AssemblyName System.IO.Compression.FileSystem
$zip = [System.IO.Compression.ZipFile]::OpenRead($apkSrc)
try {
    $entries = $zip.Entries | ForEach-Object { $_.FullName }
} finally {
    $zip.Dispose()
}
$hasDex = $entries | Where-Object { $_ -match '^classes(\d+)?\.dex$' }
$hasSo = $entries | Where-Object { $_ -eq 'lib/arm64-v8a/libgojni.so' -or $_ -like 'lib/arm64-v8a/*.so' }
$hasManifest = $entries | Where-Object { $_ -eq 'AndroidManifest.xml' }
if (-not $hasDex) { throw "APK missing classes.dex" }
if (-not $hasManifest) { throw "APK missing AndroidManifest.xml" }
if (-not $hasSo) { throw "APK missing lib/arm64-v8a native library (libgojni.so)" }
Write-Host "NATIVE LIB IN APK = PASS ($($hasSo -join ', '))"
Write-Host "APK NATIVE CONTENT = PASS"

$dist = Join-Path $Root "dist"
New-Item -ItemType Directory -Force -Path $dist | Out-Null
$apkDst = Join-Path $dist "Nyxveil-Android-v$version-debug.apk"
Copy-Item -Force $apkSrc $apkDst

$size = (Get-Item $apkDst).Length
$hash = (Get-FileHash -Algorithm SHA256 -Path $apkDst).Hash.ToLowerInvariant()
Write-Host "APK: $apkDst"
Write-Host ("Size: {0:N0} bytes" -f $size)
Write-Host "SHA256: $hash"

# Package / version sanity via aapt if available
$aapt = Get-ChildItem (Join-Path $sdk "build-tools") -Directory -ErrorAction SilentlyContinue |
    Sort-Object Name -Descending |
    ForEach-Object { Join-Path $_.FullName "aapt.exe" } |
    Where-Object { Test-Path $_ } |
    Select-Object -First 1
if ($aapt) {
    $badging = & $aapt dump badging $apkDst 2>$null
    $pkgLine = $badging | Select-String "package: " | Select-Object -First 1
    Write-Host "aapt: $pkgLine"
    if ($pkgLine -notmatch "name='ru\.nyxveil\.android") {
        throw "Unexpected package name in APK"
    }
    if ($pkgLine -notmatch "versionName='1\.0\.0") {
        throw "Unexpected versionName (want 1.0.0*)"
    }
}

if ($Install) {
    & (Join-Path $PSScriptRoot "install-apk.ps1") -Apk $apkDst
}
