#Requires -Version 5.1
param(
    [switch]$SkipNative
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
if (-not (Test-Path (Join-Path $Root "settings.gradle.kts"))) {
    throw "Cannot locate clients/android root."
}
Set-Location $Root

function Resolve-JavaHome {
    if ($env:JAVA_HOME -and (Test-Path (Join-Path $env:JAVA_HOME "bin\java.exe"))) {
        return $env:JAVA_HOME
    }
    foreach ($candidate in @(
        (Join-Path $Root "tools\jdk-17"),
        (Join-Path $env:USERPROFILE "tools\jdk-17"),
        "C:\Program Files\Microsoft\jdk-17*",
        "C:\Program Files\Eclipse Adoptium\jdk-17*"
    )) {
        $resolved = Get-Item $candidate -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($resolved -and (Test-Path (Join-Path $resolved.FullName "bin\java.exe"))) {
            return $resolved.FullName
        }
    }
    throw "JAVA_HOME / JDK 17 not found."
}

function Resolve-AndroidSdk {
    foreach ($candidate in @(
        $env:ANDROID_HOME,
        $env:ANDROID_SDK_ROOT,
        "C:\Android\Sdk",
        (Join-Path $env:LOCALAPPDATA "Android\Sdk")
    )) {
        if ($candidate -and (Test-Path $candidate)) { return $candidate }
    }
    throw "Android SDK not found."
}

$javaHome = Resolve-JavaHome
$sdk = Resolve-AndroidSdk
$env:JAVA_HOME = $javaHome
$env:ANDROID_HOME = $sdk
$env:ANDROID_SDK_ROOT = $sdk

@"
## This file is generated by scripts/build-aab.ps1
sdk.dir=$($sdk -replace '\\', '/')
"@ | Set-Content -Path (Join-Path $Root "local.properties") -Encoding ASCII

$assertCore = Join-Path $Root "..\windows\scripts\assert-frozen-core.ps1"
if (Test-Path $assertCore) {
    & $assertCore
    if ($LASTEXITCODE -ne 0) { throw "Frozen Core assert failed" }
}

if (-not $SkipNative) {
    & (Join-Path $PSScriptRoot "build-native.ps1")
    if ($LASTEXITCODE -ne 0) { throw "build-native.ps1 failed" }
}

# Optional external signing - never commit passwords.
$signingProps = Join-Path $Root "keystore.properties"
$hasEnvSigning =
    $env:NYXVEIL_STORE_FILE -and
    $env:NYXVEIL_STORE_PASSWORD -and
    $env:NYXVEIL_KEY_ALIAS -and
    $env:NYXVEIL_KEY_PASSWORD

if ($hasEnvSigning) {
    @"
storeFile=$($env:NYXVEIL_STORE_FILE -replace '\\', '/')
storePassword=$($env:NYXVEIL_STORE_PASSWORD)
keyAlias=$($env:NYXVEIL_KEY_ALIAS)
keyPassword=$($env:NYXVEIL_KEY_PASSWORD)
"@ | Set-Content -Path $signingProps -Encoding ASCII
    Write-Host "Using external signing from NYXVEIL_* env"
} elseif (Test-Path $signingProps) {
    Write-Host "Using existing keystore.properties"
} else {
    Write-Host "No signing config - release bundle unsigned candidate"
}

$gradlew = Join-Path $Root "gradlew.bat"
& $gradlew ":app:bundleRelease"
if ($LASTEXITCODE -ne 0) {
    throw "bundleRelease failed with exit code $LASTEXITCODE"
}

$version = (Get-Content (Join-Path $Root "VERSION") -Raw).Trim()
$aabSrc = Join-Path $Root "app\build\outputs\bundle\release\app-release.aab"
if (-not (Test-Path $aabSrc)) {
    throw "AAB not found: $aabSrc"
}

$dist = Join-Path $Root "dist"
New-Item -ItemType Directory -Force -Path $dist | Out-Null
$suffix = if ($hasEnvSigning -or (Test-Path $signingProps)) { "" } else { "-unsigned" }
$aabDst = Join-Path $dist "Nyxveil-Android-v$version$suffix.aab"
Copy-Item -Force $aabSrc $aabDst

$size = (Get-Item $aabDst).Length
$hash = (Get-FileHash -Algorithm SHA256 -Path $aabDst).Hash.ToLowerInvariant()
Write-Host "AAB: $aabDst"
Write-Host ("Size: {0:N0} bytes" -f $size)
Write-Host "SHA256: $hash"
Write-Host "GOOGLE PLAY UPLOAD = NO"

if ($hasEnvSigning -and (Test-Path $signingProps)) {
    Remove-Item -Force $signingProps -ErrorAction SilentlyContinue
}
