/*
================================================================================
  Nyxveil Control Plane — Database bootstrap (idempotent)
================================================================================
  Product:   Nyxveil Licensing / Control Plane
  Version:   1.0.0 (see ../VERSION)
  Target:    Microsoft SQL Server 2019+ / Azure SQL

  TIMESTAMP CONVENTION
  --------------------
  All datetime2(7) columns store Coordinated Universal Time (UTC).
  Application code MUST write DateTime with Kind=Utc (or DateTime.UtcNow /
  DateTimeOffset converted to UTC). Do not store local wall-clock times.

  IDEMPOTENCY
  -----------
  Safe to re-run after a successful install: the EF migration marker gates DDL.
  Fresh database baseline only; do not stamp an older or partial schema as current.
  All tables, columns, defaults, constraints and indexes are generated by EF.

  USAGE
  -----
  See README.md in this folder (sqlcmd / SSMS).
================================================================================
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

/* -------------------------------------------------------------------------- */
/* Configurable database name (sqlcmd)                                        */
/* Custom name: installer prepares :setvar; for manual use edit it below.    */
/* Default remains NyxveilControlPlane.                                       */
/* -------------------------------------------------------------------------- */
:setvar DatabaseName NyxveilControlPlane

IF DB_ID(N'$(DatabaseName)') IS NULL
BEGIN
    DECLARE @createSql nvarchar(500) =
        N'CREATE DATABASE ' + QUOTENAME(N'$(DatabaseName)') + N';';
    EXEC sys.sp_executesql @createSql;
    PRINT N'Created database: $(DatabaseName)';
END
ELSE
BEGIN
    PRINT N'Database already exists: $(DatabaseName)';
END
GO

USE [$(DatabaseName)];
GO

-- Required session options for filtered indexes. Do not change server or
-- database defaults: other applications may share this SQL Server instance.
SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
SET ANSI_PADDING ON;
SET ANSI_WARNINGS ON;
SET ARITHABORT ON;
SET CONCAT_NULL_YIELDS_NULL ON;
SET NUMERIC_ROUNDABORT OFF;
GO

-- BEGIN EF GENERATED BASELINE
IF OBJECT_ID(N'[__EFMigrationsHistory]') IS NULL
BEGIN
    CREATE TABLE [__EFMigrationsHistory] (
        [MigrationId] nvarchar(150) NOT NULL,
        [ProductVersion] nvarchar(32) NOT NULL,
        CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY ([MigrationId])
    );
END;
GO

BEGIN TRANSACTION;
IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetRoles] (
        [Id] nvarchar(450) NOT NULL,
        [Name] nvarchar(256) NULL,
        [NormalizedName] nvarchar(256) NULL,
        [ConcurrencyStamp] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetRoles] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetUsers] (
        [Id] nvarchar(450) NOT NULL,
        [DisplayName] nvarchar(256) NULL,
        [UserName] nvarchar(256) NULL,
        [NormalizedUserName] nvarchar(256) NULL,
        [Email] nvarchar(256) NULL,
        [NormalizedEmail] nvarchar(256) NULL,
        [EmailConfirmed] bit NOT NULL,
        [PasswordHash] nvarchar(max) NULL,
        [SecurityStamp] nvarchar(max) NULL,
        [ConcurrencyStamp] nvarchar(max) NULL,
        [PhoneNumber] nvarchar(max) NULL,
        [PhoneNumberConfirmed] bit NOT NULL,
        [TwoFactorEnabled] bit NOT NULL,
        [LockoutEnd] datetimeoffset NULL,
        [LockoutEnabled] bit NOT NULL,
        [AccessFailedCount] int NOT NULL,
        CONSTRAINT [PK_AspNetUsers] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AuditLog] (
        [Id] uniqueidentifier NOT NULL,
        [Actor] nvarchar(256) NOT NULL,
        [Action] nvarchar(128) NOT NULL,
        [EntityType] nvarchar(128) NOT NULL,
        [EntityId] nvarchar(256) NULL,
        [Timestamp] datetime2 NOT NULL,
        [IpAddress] nvarchar(64) NULL,
        [DetailsJson] nvarchar(max) NULL,
        CONSTRAINT [PK_AuditLog] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [BootstrapTokens] (
        [BootstrapId] uniqueidentifier NOT NULL,
        [Verifier] nvarchar(200) NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        [MaxUses] int NOT NULL,
        [UsedCount] int NOT NULL,
        [AllowedLocation] nvarchar(64) NULL,
        [Status] int NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NOT NULL,
        [Note] nvarchar(1024) NULL,
        CONSTRAINT [PK_BootstrapTokens] PRIMARY KEY ([BootstrapId]),
        CONSTRAINT [CK_BootstrapTokens_MaxUses] CHECK ([MaxUses] >= 1),
        CONSTRAINT [CK_BootstrapTokens_Status] CHECK ([Status] BETWEEN 0 AND 3),
        CONSTRAINT [CK_BootstrapTokens_UsedCount] CHECK ([UsedCount] >= 0 AND [UsedCount] <= [MaxUses])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [CatalogVersions] (
        [Id] uniqueidentifier NOT NULL,
        [Version] nvarchar(64) NOT NULL,
        [IssuedAt] datetime2 NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        [KeyId] nvarchar(128) NOT NULL,
        [PayloadHash] nvarchar(128) NULL,
        [CreatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_CatalogVersions] PRIMARY KEY ([Id])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Locations] (
        [LocationId] nvarchar(64) NOT NULL,
        [Code] nvarchar(64) NOT NULL,
        [Country] nvarchar(128) NOT NULL,
        [City] nvarchar(128) NOT NULL,
        [DisplayName] nvarchar(256) NOT NULL,
        [Enabled] bit NOT NULL,
        [SortOrder] int NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        [CountryCode] nvarchar(8) NULL,
        CONSTRAINT [PK_Locations] PRIMARY KEY ([LocationId]),
        CONSTRAINT [AK_Locations_Code] UNIQUE ([Code])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [PaymentEvents] (
        [Id] uniqueidentifier NOT NULL,
        [Provider] nvarchar(64) NOT NULL,
        [ExternalPaymentId] nvarchar(256) NOT NULL,
        [Status] int NOT NULL,
        [Amount] decimal(18,4) NULL,
        [Currency] nvarchar(8) NULL,
        [PayloadHash] nvarchar(128) NULL,
        [ReceivedAt] datetime2 NOT NULL,
        [ProcessedAt] datetime2 NULL,
        CONSTRAINT [PK_PaymentEvents] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_PaymentEvents_Amount] CHECK ([Amount] IS NULL OR [Amount] >= 0),
        CONSTRAINT [CK_PaymentEvents_Status] CHECK ([Status] BETWEEN 0 AND 3)
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Plans] (
        [PlanId] uniqueidentifier NOT NULL,
        [Code] nvarchar(64) NOT NULL,
        [Name] nvarchar(128) NOT NULL,
        [Status] nvarchar(64) NOT NULL,
        [DurationDays] int NOT NULL,
        [MaxDevices] int NOT NULL,
        [AllowedLocationsPolicy] nvarchar(4000) NOT NULL,
        [Permissions] nvarchar(4000) NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Plans] PRIMARY KEY ([PlanId]),
        CONSTRAINT [CK_Plans_DurationDays] CHECK ([DurationDays] >= 0),
        CONSTRAINT [CK_Plans_MaxDevices] CHECK ([MaxDevices] >= 1),
        CONSTRAINT [CK_Plans_Status] CHECK ([Status] IN (N'Active', N'Disabled', N'Retired'))
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Revocations] (
        [Id] uniqueidentifier NOT NULL,
        [Type] int NOT NULL,
        [TargetId] nvarchar(256) NOT NULL,
        [Reason] nvarchar(1024) NULL,
        [CreatedAt] datetime2 NOT NULL,
        [CreatedBy] nvarchar(256) NOT NULL,
        [Version] bigint NOT NULL,
        CONSTRAINT [PK_Revocations] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_Revocations_Type] CHECK ([Type] BETWEEN 0 AND 2),
        CONSTRAINT [CK_Revocations_Version] CHECK ([Version] >= 1)
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [SigningKeysMetadata] (
        [Id] uniqueidentifier NOT NULL,
        [KeyId] nvarchar(128) NOT NULL,
        [PublicKey] varbinary(32) NOT NULL,
        [ProtectedPrivateKey] varbinary(max) NOT NULL,
        [Status] int NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [RetiredAt] datetime2 NULL,
        CONSTRAINT [PK_SigningKeysMetadata] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_SigningKeysMetadata_PublicKeyLen] CHECK (DATALENGTH([PublicKey]) = 32),
        CONSTRAINT [CK_SigningKeysMetadata_Status] CHECK ([Status] BETWEEN 0 AND 2)
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [SystemSettings] (
        [Key] nvarchar(128) NOT NULL,
        [Value] nvarchar(max) NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        [UpdatedBy] nvarchar(256) NULL,
        CONSTRAINT [PK_SystemSettings] PRIMARY KEY ([Key])
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [TicketAudits] (
        [Id] uniqueidentifier NOT NULL,
        [TicketId] nvarchar(128) NOT NULL,
        [LicenseId] uniqueidentifier NOT NULL,
        [DeviceId] nvarchar(128) NOT NULL,
        [IssuedAt] datetime2 NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        [LocationsJson] nvarchar(4000) NOT NULL,
        [NodeScopeJson] nvarchar(4000) NOT NULL,
        [Action] nvarchar(32) NOT NULL,
        CONSTRAINT [PK_TicketAudits] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_TicketAudits_Action] CHECK ([Action] IN (N'issue', N'refresh'))
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Users] (
        [UserId] uniqueidentifier NOT NULL,
        [ExternalId] nvarchar(256) NULL,
        [Email] nvarchar(320) NULL,
        [DisplayName] nvarchar(256) NULL,
        [Status] nvarchar(64) NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Users] PRIMARY KEY ([UserId]),
        CONSTRAINT [CK_Users_Status] CHECK ([Status] IN (N'Active', N'Disabled', N'Deleted'))
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetRoleClaims] (
        [Id] int NOT NULL IDENTITY,
        [RoleId] nvarchar(450) NOT NULL,
        [ClaimType] nvarchar(max) NULL,
        [ClaimValue] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetUserClaims] (
        [Id] int NOT NULL IDENTITY,
        [UserId] nvarchar(450) NOT NULL,
        [ClaimType] nvarchar(max) NULL,
        [ClaimValue] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY ([Id]),
        CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetUserLogins] (
        [LoginProvider] nvarchar(450) NOT NULL,
        [ProviderKey] nvarchar(450) NOT NULL,
        [ProviderDisplayName] nvarchar(max) NULL,
        [UserId] nvarchar(450) NOT NULL,
        CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY ([LoginProvider], [ProviderKey]),
        CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetUserRoles] (
        [UserId] nvarchar(450) NOT NULL,
        [RoleId] nvarchar(450) NOT NULL,
        CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY ([UserId], [RoleId]),
        CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY ([RoleId]) REFERENCES [AspNetRoles] ([Id]) ON DELETE CASCADE,
        CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [AspNetUserTokens] (
        [UserId] nvarchar(450) NOT NULL,
        [LoginProvider] nvarchar(450) NOT NULL,
        [Name] nvarchar(450) NOT NULL,
        [Value] nvarchar(max) NULL,
        CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY ([UserId], [LoginProvider], [Name]),
        CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY ([UserId]) REFERENCES [AspNetUsers] ([Id]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Nodes] (
        [NodeId] nvarchar(128) NOT NULL,
        [LocationId] nvarchar(64) NOT NULL,
        [DisplayName] nvarchar(256) NOT NULL,
        [Status] int NOT NULL,
        [Enabled] bit NOT NULL,
        [TestOnly] bit NOT NULL,
        [Draining] bit NOT NULL,
        [ProtocolVersion] int NOT NULL,
        [ServerVersion] nvarchar(64) NULL,
        [ServerName] nvarchar(256) NULL,
        [SpkiPin] varbinary(32) NULL,
        [PublicIdentity] varbinary(32) NOT NULL,
        [Capacity] int NOT NULL,
        [CurrentSessions] int NOT NULL,
        [HealthStatus] nvarchar(64) NULL,
        [LastSeenAt] datetime2 NULL,
        [CreatedAt] datetime2 NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        [ConfigVersion] bigint NOT NULL,
        CONSTRAINT [PK_Nodes] PRIMARY KEY ([NodeId]),
        CONSTRAINT [CK_Nodes_Capacity] CHECK ([Capacity] >= 0),
        CONSTRAINT [CK_Nodes_CurrentSessions] CHECK ([CurrentSessions] >= 0),
        CONSTRAINT [CK_Nodes_ProtocolVersion] CHECK ([ProtocolVersion] >= 0 AND [ProtocolVersion] <= 65535),
        CONSTRAINT [CK_Nodes_PublicIdentityLen] CHECK (DATALENGTH([PublicIdentity]) = 32),
        CONSTRAINT [CK_Nodes_Status] CHECK ([Status] BETWEEN 0 AND 3),
        CONSTRAINT [FK_Nodes_Locations_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [Locations] ([LocationId]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Licenses] (
        [LicenseId] uniqueidentifier NOT NULL,
        [UserId] uniqueidentifier NULL,
        [LicenseKeyVerifier] nvarchar(200) NOT NULL,
        [Role] nvarchar(64) NOT NULL,
        [PlanId] uniqueidentifier NOT NULL,
        [Status] int NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [ActivatedAt] datetime2 NULL,
        [ExpiresAt] datetime2 NULL,
        [MaxDevices] int NOT NULL,
        [Note] nvarchar(1024) NULL,
        [ExternalPaymentId] nvarchar(256) NULL,
        [CreatedBy] nvarchar(256) NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_Licenses] PRIMARY KEY ([LicenseId]),
        CONSTRAINT [CK_Licenses_MaxDevices] CHECK ([MaxDevices] >= 1),
        CONSTRAINT [CK_Licenses_Status] CHECK ([Status] BETWEEN 0 AND 4),
        CONSTRAINT [FK_Licenses_Plans_PlanId] FOREIGN KEY ([PlanId]) REFERENCES [Plans] ([PlanId]) ON DELETE NO ACTION,
        CONSTRAINT [FK_Licenses_Users_UserId] FOREIGN KEY ([UserId]) REFERENCES [Users] ([UserId]) ON DELETE SET NULL
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeConfigs] (
        [NodeId] nvarchar(128) NOT NULL,
        [Enabled] bit NOT NULL,
        [Draining] bit NOT NULL,
        [MaintenanceMode] bit NOT NULL,
        [TransportPolicyJson] nvarchar(max) NOT NULL,
        [EchPolicyJson] nvarchar(max) NULL,
        [Mtu] int NULL,
        [Capacity] int NOT NULL,
        [MinimumServerVersion] nvarchar(64) NULL,
        [MinimumProtocolVersion] int NULL,
        [ConfigVersion] bigint NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_NodeConfigs] PRIMARY KEY ([NodeId]),
        CONSTRAINT [CK_NodeConfigs_Capacity] CHECK ([Capacity] >= 0),
        CONSTRAINT [CK_NodeConfigs_ConfigVersion] CHECK ([ConfigVersion] >= 1),
        CONSTRAINT [CK_NodeConfigs_MinimumProtocolVersion] CHECK ([MinimumProtocolVersion] IS NULL OR ([MinimumProtocolVersion] >= 0 AND [MinimumProtocolVersion] <= 65535)),
        CONSTRAINT [CK_NodeConfigs_Mtu] CHECK ([Mtu] IS NULL OR ([Mtu] >= 576 AND [Mtu] <= 9000)),
        CONSTRAINT [FK_NodeConfigs_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeCredentials] (
        [NodeId] nvarchar(128) NOT NULL,
        [PublicKey] varbinary(32) NOT NULL,
        [CredentialIssuedAt] datetime2 NOT NULL,
        [NodeAuthSecretVerifier] nvarchar(200) NULL,
        [LastAuthAt] datetime2 NULL,
        [LastCoreTokenUnix] bigint NULL,
        CONSTRAINT [PK_NodeCredentials] PRIMARY KEY ([NodeId]),
        CONSTRAINT [CK_NodeCredentials_PublicKeyLen] CHECK (DATALENGTH([PublicKey]) = 32),
        CONSTRAINT [FK_NodeCredentials_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeEndpoints] (
        [Id] uniqueidentifier NOT NULL,
        [NodeId] nvarchar(128) NOT NULL,
        [Host] nvarchar(256) NOT NULL,
        [Port] int NOT NULL,
        [AddressFamily] nvarchar(16) NOT NULL,
        [Priority] int NOT NULL,
        [Enabled] bit NOT NULL,
        CONSTRAINT [PK_NodeEndpoints] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_NodeEndpoints_AddressFamily] CHECK ([AddressFamily] IN (N'ipv4', N'ipv6', N'hostname')),
        CONSTRAINT [CK_NodeEndpoints_Port] CHECK ([Port] >= 1 AND [Port] <= 65535),
        CONSTRAINT [FK_NodeEndpoints_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeHealth] (
        [NodeId] nvarchar(128) NOT NULL,
        [CpuPercent] float NOT NULL,
        [MemoryPercent] float NOT NULL,
        [MemoryBytes] bigint NULL,
        [UptimeSeconds] bigint NULL,
        [ActiveSessions] int NOT NULL,
        [NetworkRxRate] float NULL,
        [NetworkTxRate] float NULL,
        [LoadAverage] float NULL,
        [Healthy] bit NOT NULL,
        [UpdatedAt] datetime2 NOT NULL,
        CONSTRAINT [PK_NodeHealth] PRIMARY KEY ([NodeId]),
        CONSTRAINT [CK_NodeHealth_ActiveSessions] CHECK ([ActiveSessions] >= 0),
        CONSTRAINT [CK_NodeHealth_CpuPercent] CHECK ([CpuPercent] >= 0 AND [CpuPercent] <= 100),
        CONSTRAINT [CK_NodeHealth_MemoryPercent] CHECK ([MemoryPercent] >= 0 AND [MemoryPercent] <= 100),
        CONSTRAINT [FK_NodeHealth_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeMetrics] (
        [Id] uniqueidentifier NOT NULL,
        [NodeId] nvarchar(128) NOT NULL,
        [Timestamp] datetime2 NOT NULL,
        [CpuPercent] float NOT NULL,
        [MemoryPercent] float NOT NULL,
        [MemoryBytes] bigint NULL,
        [ActiveSessions] int NOT NULL,
        [NetworkRxRate] float NULL,
        [NetworkTxRate] float NULL,
        [UptimeSeconds] bigint NULL,
        CONSTRAINT [PK_NodeMetrics] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_NodeMetrics_ActiveSessions] CHECK ([ActiveSessions] >= 0),
        CONSTRAINT [FK_NodeMetrics_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeTransports] (
        [Id] uniqueidentifier NOT NULL,
        [NodeId] nvarchar(128) NOT NULL,
        [TransportType] nvarchar(16) NOT NULL,
        [Enabled] bit NOT NULL,
        [Priority] int NOT NULL,
        CONSTRAINT [PK_NodeTransports] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_NodeTransports_TransportType] CHECK ([TransportType] IN (N'tls', N'quic')),
        CONSTRAINT [FK_NodeTransports_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [Devices] (
        [Id] uniqueidentifier NOT NULL,
        [ClientDeviceId] nvarchar(128) NOT NULL,
        [LicenseId] uniqueidentifier NOT NULL,
        [PublicKey] varbinary(64) NOT NULL,
        [Platform] nvarchar(64) NULL,
        [DeviceName] nvarchar(256) NULL,
        [Status] int NOT NULL,
        [CreatedAt] datetime2 NOT NULL,
        [LastSeenAt] datetime2 NULL,
        [RevokedAt] datetime2 NULL,
        CONSTRAINT [PK_Devices] PRIMARY KEY ([Id]),
        CONSTRAINT [CK_Devices_PublicKeyLen] CHECK (DATALENGTH([PublicKey]) >= 32 AND DATALENGTH([PublicKey]) <= 64),
        CONSTRAINT [CK_Devices_Status] CHECK ([Status] BETWEEN 0 AND 2),
        CONSTRAINT [FK_Devices_Licenses_LicenseId] FOREIGN KEY ([LicenseId]) REFERENCES [Licenses] ([LicenseId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [LicenseAllowedLocations] (
        [LicenseId] uniqueidentifier NOT NULL,
        [LocationId] nvarchar(64) NOT NULL,
        CONSTRAINT [PK_LicenseAllowedLocations] PRIMARY KEY ([LicenseId], [LocationId]),
        CONSTRAINT [FK_LicenseAllowedLocations_Licenses_LicenseId] FOREIGN KEY ([LicenseId]) REFERENCES [Licenses] ([LicenseId]) ON DELETE CASCADE,
        CONSTRAINT [FK_LicenseAllowedLocations_Locations_LocationId] FOREIGN KEY ([LocationId]) REFERENCES [Locations] ([LocationId]) ON DELETE NO ACTION
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AspNetRoleClaims_RoleId] ON [AspNetRoleClaims] ([RoleId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    EXEC(N'CREATE UNIQUE INDEX [RoleNameIndex] ON [AspNetRoles] ([NormalizedName]) WHERE [NormalizedName] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AspNetUserClaims_UserId] ON [AspNetUserClaims] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AspNetUserLogins_UserId] ON [AspNetUserLogins] ([UserId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AspNetUserRoles_RoleId] ON [AspNetUserRoles] ([RoleId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [EmailIndex] ON [AspNetUsers] ([NormalizedEmail]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    EXEC(N'CREATE UNIQUE INDEX [UserNameIndex] ON [AspNetUsers] ([NormalizedUserName]) WHERE [NormalizedUserName] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AuditLog_EntityType_EntityId] ON [AuditLog] ([EntityType], [EntityId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_AuditLog_Timestamp] ON [AuditLog] ([Timestamp]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_BootstrapTokens_Status_ExpiresAt] ON [BootstrapTokens] ([Status], [ExpiresAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_BootstrapTokens_Verifier] ON [BootstrapTokens] ([Verifier]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_CatalogVersions_IssuedAt] ON [CatalogVersions] ([IssuedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_CatalogVersions_Version] ON [CatalogVersions] ([Version]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Devices_LicenseId] ON [Devices] ([LicenseId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Devices_LicenseId_ClientDeviceId] ON [Devices] ([LicenseId], [ClientDeviceId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Devices_Status] ON [Devices] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_LicenseAllowedLocations_LocationId] ON [LicenseAllowedLocations] ([LocationId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Licenses_LicenseKeyVerifier] ON [Licenses] ([LicenseKeyVerifier]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Licenses_PlanId] ON [Licenses] ([PlanId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Licenses_Status_ExpiresAt] ON [Licenses] ([Status], [ExpiresAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    EXEC(N'CREATE INDEX [IX_Licenses_UserId] ON [Licenses] ([UserId]) WHERE [UserId] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Locations_Code] ON [Locations] ([Code]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Locations_Enabled_SortOrder] ON [Locations] ([Enabled], [SortOrder]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeEndpoints_NodeId] ON [NodeEndpoints] ([NodeId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeHealth_Healthy] ON [NodeHealth] ([Healthy]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeHealth_UpdatedAt] ON [NodeHealth] ([UpdatedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeMetrics_NodeId_Timestamp] ON [NodeMetrics] ([NodeId], [Timestamp]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Nodes_Enabled_TestOnly] ON [Nodes] ([Enabled], [TestOnly]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Nodes_LocationId] ON [Nodes] ([LocationId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Nodes_Status] ON [Nodes] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeTransports_NodeId] ON [NodeTransports] ([NodeId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_PaymentEvents_Provider_ExternalPaymentId] ON [PaymentEvents] ([Provider], [ExternalPaymentId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_PaymentEvents_Status_ReceivedAt] ON [PaymentEvents] ([Status], [ReceivedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_Plans_Code] ON [Plans] ([Code]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Revocations_TargetId] ON [Revocations] ([TargetId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Revocations_Type_TargetId] ON [Revocations] ([Type], [TargetId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_Revocations_Version] ON [Revocations] ([Version]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE UNIQUE INDEX [IX_SigningKeysMetadata_KeyId] ON [SigningKeysMetadata] ([KeyId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_SigningKeysMetadata_Status] ON [SigningKeysMetadata] ([Status]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TicketAudits_LicenseId_IssuedAt] ON [TicketAudits] ([LicenseId], [IssuedAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_TicketAudits_TicketId] ON [TicketAudits] ([TicketId]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    EXEC(N'CREATE INDEX [IX_Users_Email] ON [Users] ([Email]) WHERE [Email] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    EXEC(N'CREATE INDEX [IX_Users_ExternalId] ON [Users] ([ExternalId]) WHERE [ExternalId] IS NOT NULL');
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE TABLE [NodeRequestNonces] (
        [NodeId] nvarchar(128) NOT NULL,
        [NonceHash] varchar(64) NOT NULL,
        [Timestamp] datetime2 NOT NULL,
        [ExpiresAt] datetime2 NOT NULL,
        CONSTRAINT [PK_NodeRequestNonces] PRIMARY KEY ([NodeId], [NonceHash]),
        CONSTRAINT [FK_NodeRequestNonces_Nodes_NodeId] FOREIGN KEY ([NodeId]) REFERENCES [Nodes] ([NodeId]) ON DELETE CASCADE
    );
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    CREATE INDEX [IX_NodeRequestNonces_ExpiresAt] ON [NodeRequestNonces] ([ExpiresAt]);
END;

IF NOT EXISTS (
    SELECT * FROM [__EFMigrationsHistory]
    WHERE [MigrationId] = N'20260904155703_InitialCreate'
)
BEGIN
    INSERT INTO [__EFMigrationsHistory] ([MigrationId], [ProductVersion])
    VALUES (N'20260904155703_InitialCreate', N'10.0.11');
END;

COMMIT;
GO
-- END EF GENERATED BASELINE
